version: '3.9'

services:
  app:
    container_name: nestjs_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3333:3333'

    depends_on:
      - database
    environment:
      - NODE_ENV=production
    restart: always

  database:
    container_name: postgresdb
    image: postgres:alpine
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pg_password
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_db:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_db:
